# Generated by Django 5.2.4 on 2025-10-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
