# Generated by Django 5.2.7 on 2025-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_delete_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
