# Generated by Django 5.2.7 on 2025-11-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewtable_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
